### ISSUE TITLE
Country issues 

### ISSUE THREAD

**Issue by mverma29** [samclifford/MeganVermaMsc#1]
kosovo doesn't have an official iso code-- what are implications for nations that are younger than datasets in RESPICAR?

**Comment by samclifford** [comment]
This was raised here https://github.com/samclifford/MeganVermaMsc/blob/d32d9ed5d371469ef854df7c95bd1cb57a3af6df/task_glm.Rmd#L226 

We should have a look at which countries in the RESPICAR data have had border changes and whether those occurred after data collection. Anything collected after the most recent border change won't be an issue.

Thinking Sudan, Israel, former Yugoslav republics.

**Comment by samclifford** [comment]
Using border change info from [Wikipedia](https://en.wikipedia.org/wiki/List_of_national_border_changes_(1914%E2%80%93present)) and a string matching pattern `"(Sudan|slav|Israel|Palest|Croatia|Serbia|Montenegro|Bosnia|Herz|Kosov|FYR|Macedonia|Ethiopia|Eritrea|Somal|Namibia|Hong|Yemen|Kuwait|Iraq|Macau|Czech|Slovak|Russia|Soviet|Latvia|Lithuania|Estonia|Belarus|Ukraine|Moldova|Georgia|Armenia|Azerbaijan|Germany|Palau)"` we have data from the following countries that cover the following years

|Country                 | ISO 3166-1|  Min year started |  Max year ended |
|:-----------------------|----------:|----:|----:|
|Czechia                 |        203| 2004| 2010|
|Ethiopia                |        231| 2006| 2007|
|Hong Kong SAR China     |        344| 1999| 2000|
|Israel                  |        376| 1993| 2011|
|Palestinian Territories |        275| 2009| 2011|
|Russia                  |        643| 1993| 2003|
|Slovakia                |        703| 1993| 1994|
|South Sudan             |        728| 2000| 2000|

There are no studies done in the Soviet Union, Czechoslovakia or Yugoslavia so we don't need to go digging further to reallocate them to other countries that have succeeded those states. Hong Kong SAR studies are after the handover from the UK. Ethiopia's studies are after the independence of Eritrea, similarly for Sudan and South Sudan. 

That leaves just Israel and Palestine. We should probably check the papers for these countries to see if the study region has changed hands since publication.

**Comment by mverma29** [comment]
22 israeli studies & 5 palestinian studies: need to check respicar_israel & respicar_palestine

**Comment by samclifford** [comment]
I've looked over the studies mentioned (22 Israeli data sets in 10 studies, 5 Palestinian in 2). No changes need to be made to the country allocation.

|ISO 3166-1 |id    |location                   |notes                                                                                                                                                                                             |
|:----------|:-----|:--------------------------|:-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|376        |38686 |Be'er Sheva                |Has been part of Israel since its capture in October 1948 and granting to Israel during the 1949 Armistice Agreement                                                                              |
|376        |19645 |Be'er Sheva                |Has been part of Israel since its capture in October 1948 and granting to Israel during the 1949 Armistice Agreement                                                                              |
|376        |39156 |Be'er Ya'akov              |Was on front line of 1948 war but has been part of Israel since                                                                                                                                   |
|376        |40459 |Negev region               |1947 UN Partition plan put most of it in Israel, 1947-49 War of Independence saw Israel secure the whole region                                                                                   |
|376        |39396 |Central Israel             |Central Israel                                                                                                                                                                                    |
|376        |40349 |IDF training unit compound |In Israel                                                                                                                                                                                         |
|376        |40716 |Negev region               |1947 UN Partition plan put most of it in Israel, 1947-49 War of Independence saw Israel secure the whole region                                                                                   |
|376        |22247 |Negev region               |1947 UN Partition plan put most of it in Israel, 1947-49 War of Independence saw Israel secure the whole region                                                                                   |
|376        |40773 |IDF training unit compound |In Israel                                                                                                                                                                                         |
|376        |22590 |East Jerusalem             |Occupied by Israel since 1967, UN General Assembly resolution 67/19 (2012) considers East Jerusalem part of Occupied Palestine Territory though East Jerusalem is de facto administered by Israel |
|275        |22590 |West Bank                  |Occupied by Israel 1967 and remained under military control until 1982. Palestinian Territory since 1993                                                                                          |
|275        |730   |Gaza Strip                 |Oslo Accords in 1993 established Palestinian control, which took force in 1994                                                                                                                    |
