### ISSUE TITLE
function for "greatest staleness" of a covariate 

### ISSUE THREAD

**Issue by mverma29** [samclifford/MeganVermaMsc#28]
need to find the "most stale" value for each covariate matched to each study (when not matched on exact start year) for write-up purposes

**Comment by samclifford** [comment]
This should be a matter of checking if the row in the socio data is NA and then mutating a new variable of the current year if it isn't, then using the downup fill on that new column. Then find the difference between imputed year and year of the data set. Might need to read in the variable name with match call and name the new year column appropriately so that we can keep them all together in the respicar_socio data frame.

**Comment by samclifford** [comment]
The function is incorporated and now returns a long data frame where each row is a covariate for a study (ids are included). I suggest you have a think about what sort of summary statistics you'd like to report for the staleness and make sure the data dictionary has appropriate columns.
